name: Deploy DataforDocs Github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Config
      # with:
      #   persist-credentials: false
      run: |
        git config --global user.email "meishenlieshou@gmail.com"
        git config --global user.name "meishenlieshou"
    - run: yarn
    - run: yarn build
    #- run: node patchURL.js
    - run: yarn deploy
      env:
        GIT_USER: ${{ github.actor }}:${{ github.token }}
    # - name: Use Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '18.7.0'
    # - name: Install and Build
    #   run: |
    #     npm install
    #     npm run build
    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
    #     BUILD_SCRIPT: npm install && npm run build
